### ISSUE TITLE
error

### ISSUE THREAD

**Issue by farhan-helmy** [xputerax/employees-web#11]
npm run development

error

 error  in ./resources/js/views/Statistics.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\DEV\employees-web\node_modules\@vue\component-compiler-utils\dist\parse.js:14:23)
    at Object.module.exports (D:\DEV\employees-web\node_modules\vue-loader\lib\index.js:67:22)

**Comment by xputerax** [comment]
ni project lama oi, aku dah abandon
